"""Constants mirrored from ygopro-core's ocgapi_constants.h."""

LOCATION_DECK = 0x01
LOCATION_HAND = 0x02
LOCATION_MZONE = 0x04
LOCATION_SZONE = 0x08
LOCATION_GRAVE = 0x10
LOCATION_REMOVED = 0x20
LOCATION_EXTRA = 0x40
LOCATION_OVERLAY = 0x80

POS_FACEUP_ATTACK = 0x1
POS_FACEDOWN_ATTACK = 0x2
POS_FACEUP_DEFENSE = 0x4
POS_FACEDOWN_DEFENSE = 0x8
POS_FACEDOWN = POS_FACEDOWN_ATTACK | POS_FACEDOWN_DEFENSE

TYPE_XYZ = 0x800000
TYPE_PENDULUM = 0x1000000
TYPE_LINK = 0x4000000

DUEL_PZONE = 0x800
DUEL_EMZONE = 0x2000
DUEL_FSX_MMZONE = 0x4000
DUEL_TRAP_MONSTERS_NOT_USE_ZONE = 0x8000
DUEL_TRIGGER_ONLY_IN_LOCATION = 0x20000

#: Master Rule 5 - the ruleset current Yu-Gi-Oh actually uses.
MASTER_RULE_5 = (
    DUEL_PZONE
    | DUEL_EMZONE
    | DUEL_FSX_MMZONE
    | DUEL_TRAP_MONSTERS_NOT_USE_ZONE
    | DUEL_TRIGGER_ONLY_IN_LOCATION
)

# Message ids we care about. The full set is ~60; these are the ones that
# either ask for a decision or report an opponent's interruption.
MSG_RETRY = 1
MSG_HINT = 2
MSG_WIN = 5
MSG_SELECT_BATTLECMD = 10
MSG_SELECT_IDLECMD = 11
MSG_SELECT_EFFECTYN = 12
MSG_SELECT_YESNO = 13
MSG_SELECT_OPTION = 14
MSG_SELECT_CARD = 15
MSG_SELECT_CHAIN = 16
MSG_SELECT_PLACE = 18
MSG_SELECT_POSITION = 19
MSG_SELECT_TRIBUTE = 20
MSG_SORT_CARD = 24
MSG_SELECT_UNSELECT_CARD = 26
MSG_SHUFFLE_DECK = 32
MSG_DRAW = 90
MSG_NEW_TURN = 40
MSG_NEW_PHASE = 41
MSG_CHAINING = 70
MSG_CHAINED = 71
MSG_CHAIN_SOLVING = 72
MSG_CHAIN_SOLVED = 73
MSG_CHAIN_END = 74

#: Messages that require a response before the duel can continue.
DECISION_MESSAGES = frozenset({
    MSG_SELECT_BATTLECMD, MSG_SELECT_IDLECMD, MSG_SELECT_EFFECTYN,
    MSG_SELECT_YESNO, MSG_SELECT_OPTION, MSG_SELECT_CARD, MSG_SELECT_CHAIN,
    MSG_SELECT_PLACE, MSG_SELECT_POSITION, MSG_SELECT_TRIBUTE,
    MSG_SORT_CARD, MSG_SELECT_UNSELECT_CARD,
})

MSG_NAMES = {
    v: k for k, v in list(globals().items())
    if k.startswith("MSG_") and isinstance(v, int)
}
