"""Constants mirrored from ygopro-core's ocgapi_constants.h."""

LOCATION_DECK = 0x01
LOCATION_HAND = 0x02
LOCATION_MZONE = 0x04
LOCATION_SZONE = 0x08
LOCATION_GRAVE = 0x10
LOCATION_REMOVED = 0x20
LOCATION_EXTRA = 0x40
LOCATION_OVERLAY = 0x80

POS_FACEUP_ATTACK = 0x1
POS_FACEDOWN_ATTACK = 0x2
POS_FACEUP_DEFENSE = 0x4
POS_FACEDOWN_DEFENSE = 0x8
POS_FACEDOWN = POS_FACEDOWN_ATTACK | POS_FACEDOWN_DEFENSE
POS_FACEUP = POS_FACEUP_ATTACK | POS_FACEUP_DEFENSE
POS_ATTACK = POS_FACEUP_ATTACK | POS_FACEDOWN_ATTACK
POS_DEFENSE = POS_FACEUP_DEFENSE | POS_FACEDOWN_DEFENSE

TYPE_MONSTER = 0x1
TYPE_SPELL = 0x2
TYPE_TRAP = 0x4
#: Vanilla. Normal monsters have no Lua script at all, which is why a
#: script the core cannot find is only worth reporting for other types.
TYPE_NORMAL = 0x10
TYPE_XYZ = 0x800000
TYPE_PENDULUM = 0x1000000
TYPE_LINK = 0x4000000

# Duel option flags. Most of these exist only because EDOPro's puzzle scripts
# select older rulesets - a normal duel here is Master Rule 5 and needs the
# handful below MASTER_RULE_5.
DUEL_TEST_MODE = 0x01
DUEL_ATTACK_FIRST_TURN = 0x02
DUEL_USE_TRAPS_IN_NEW_CHAIN = 0x04
DUEL_6_STEP_BATLLE_STEP = 0x08          # sic - the header misspells it
DUEL_PSEUDO_SHUFFLE = 0x10
DUEL_TRIGGER_WHEN_PRIVATE_KNOWLEDGE = 0x20
DUEL_SIMPLE_AI = 0x40
DUEL_OCG_OBSOLETE_IGNITION = 0x100
DUEL_1ST_TURN_DRAW = 0x200
DUEL_1_FACEUP_FIELD = 0x400
DUEL_PZONE = 0x800
DUEL_SEPARATE_PZONE = 0x1000
DUEL_EMZONE = 0x2000
DUEL_FSX_MMZONE = 0x4000
DUEL_TRAP_MONSTERS_NOT_USE_ZONE = 0x8000
DUEL_RETURN_TO_DECK_TRIGGERS = 0x10000
DUEL_TRIGGER_ONLY_IN_LOCATION = 0x20000
DUEL_SPSUMMON_ONCE_OLD_NEGATE = 0x40000
DUEL_CANNOT_SUMMON_OATH_OLD = 0x80000
DUEL_NO_STANDBY_PHASE = 0x100000
DUEL_NO_MAIN_PHASE_2 = 0x200000
DUEL_3_COLUMNS_FIELD = 0x400000
DUEL_DRAW_UNTIL_5 = 0x800000
DUEL_NO_HAND_LIMIT = 0x1000000
DUEL_UNLIMITED_SUMMONS = 0x2000000
DUEL_INVERTED_QUICK_PRIORITY = 0x4000000
DUEL_EQUIP_NOT_SENT_IF_MISSING_TARGET = 0x8000000
DUEL_0_ATK_DESTROYED = 0x10000000
DUEL_STORE_ATTACK_REPLAYS = 0x20000000
DUEL_SINGLE_CHAIN_IN_DAMAGE_SUBSTEP = 0x40000000
DUEL_CAN_REPOS_IF_NON_SUMPLAYER = 0x80000000
DUEL_TCG_SEGOC_NONPUBLIC = 0x100000000
DUEL_TCG_SEGOC_FIRSTTRIGGER = 0x200000000
DUEL_TCG_FAST_EFFECT_IGNITION = 0x400000000
DUEL_EXTRA_DECK_RITUAL = 0x800000000

# Ruleset presets. The header composes these from the flags above; so do we,
# and tests/test_constants.py resolves the header's expressions to check that
# our composition still matches theirs.
DUEL_MODE_MR1 = (
    DUEL_OCG_OBSOLETE_IGNITION | DUEL_1ST_TURN_DRAW | DUEL_1_FACEUP_FIELD
    | DUEL_SPSUMMON_ONCE_OLD_NEGATE | DUEL_RETURN_TO_DECK_TRIGGERS
    | DUEL_CANNOT_SUMMON_OATH_OLD
)
DUEL_MODE_MR2 = (
    DUEL_1ST_TURN_DRAW | DUEL_1_FACEUP_FIELD | DUEL_SPSUMMON_ONCE_OLD_NEGATE
    | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD
)
DUEL_MODE_MR3 = (
    DUEL_PZONE | DUEL_SEPARATE_PZONE | DUEL_SPSUMMON_ONCE_OLD_NEGATE
    | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD
)
DUEL_MODE_MR4 = (
    DUEL_PZONE | DUEL_EMZONE | DUEL_SPSUMMON_ONCE_OLD_NEGATE
    | DUEL_RETURN_TO_DECK_TRIGGERS | DUEL_CANNOT_SUMMON_OATH_OLD
)
DUEL_MODE_MR5 = (
    DUEL_PZONE | DUEL_EMZONE | DUEL_FSX_MMZONE
    | DUEL_TRAP_MONSTERS_NOT_USE_ZONE | DUEL_TRIGGER_ONLY_IN_LOCATION
)
DUEL_MODE_SPEED = (
    DUEL_3_COLUMNS_FIELD | DUEL_NO_MAIN_PHASE_2
    | DUEL_TRAP_MONSTERS_NOT_USE_ZONE | DUEL_TRIGGER_ONLY_IN_LOCATION
)
DUEL_MODE_RUSH = (
    DUEL_3_COLUMNS_FIELD | DUEL_NO_MAIN_PHASE_2 | DUEL_NO_STANDBY_PHASE
    | DUEL_1ST_TURN_DRAW | DUEL_INVERTED_QUICK_PRIORITY | DUEL_DRAW_UNTIL_5
    | DUEL_NO_HAND_LIMIT | DUEL_UNLIMITED_SUMMONS
    | DUEL_TRAP_MONSTERS_NOT_USE_ZONE | DUEL_TRIGGER_ONLY_IN_LOCATION
    | DUEL_EXTRA_DECK_RITUAL
)

#: Master Rule 5 - the ruleset current Yu-Gi-Oh actually uses.
MASTER_RULE_5 = DUEL_MODE_MR5

#: ReloadFieldBegin's second argument, by Master Rule number. Puzzles pass
#: 2/3/4/5 here, or omit it - libdebug.cpp defaults the argument to 3.
MASTER_RULES = {
    1: DUEL_MODE_MR1, 2: DUEL_MODE_MR2, 3: DUEL_MODE_MR3,
    4: DUEL_MODE_MR4, 5: DUEL_MODE_MR5,
}
DEFAULT_PUZZLE_RULE = 3

# Message ids we care about. The full set is ~60; these are the ones that
# either ask for a decision or report an opponent's interruption.
MSG_RETRY = 1
MSG_HINT = 2
MSG_WIN = 5
MSG_SELECT_BATTLECMD = 10
MSG_SELECT_IDLECMD = 11
MSG_SELECT_EFFECTYN = 12
MSG_SELECT_YESNO = 13
MSG_SELECT_OPTION = 14
MSG_SELECT_CARD = 15
MSG_SELECT_CHAIN = 16
MSG_SELECT_PLACE = 18
MSG_SELECT_POSITION = 19
MSG_SELECT_DISFIELD = 24
MSG_SELECT_TRIBUTE = 20
MSG_SORT_CARD = 25
MSG_SELECT_UNSELECT_CARD = 26
MSG_SHUFFLE_DECK = 32
MSG_DRAW = 90
MSG_NEW_TURN = 40
MSG_NEW_PHASE = 41
MSG_CHAINING = 70
MSG_CHAINED = 71
MSG_CHAIN_SOLVING = 72
MSG_CHAIN_SOLVED = 73
MSG_CHAIN_END = 74
# Emitted by Debug.SetAIName / Debug.ShowHint, which every puzzle script uses.
# Neither asks for a decision; they are here so a transcript shows a name
# rather than a bare id.
MSG_AI_NAME = 163
MSG_SHOW_HINT = 164

#: Messages that require a response before the duel can continue.
DECISION_MESSAGES = frozenset({
    MSG_SELECT_BATTLECMD, MSG_SELECT_IDLECMD, MSG_SELECT_EFFECTYN,
    MSG_SELECT_YESNO, MSG_SELECT_OPTION, MSG_SELECT_CARD, MSG_SELECT_CHAIN,
    MSG_SELECT_PLACE, MSG_SELECT_POSITION, MSG_SELECT_TRIBUTE,
    MSG_SELECT_DISFIELD,
    MSG_SORT_CARD, MSG_SELECT_UNSELECT_CARD,
})

# MSG_WIN reasons (processor.cpp).
WIN_REASON_LP = 1        # life points reached 0
WIN_REASON_DECKOUT = 2   # `overdraw` - tried to draw from an empty deck

MSG_NAMES = {
    v: k for k, v in list(globals().items())
    if k.startswith("MSG_") and isinstance(v, int)
}
